### ISSUE TITLE
Extend Revision model

### ISSUE THREAD

**Issue by achancu** [VarboxInternational/varbox-issues#4]
- Laravel Version: 7.24.0
- Varbox Version: 1.0.0

### What are you trying to achieve (screenshots might help):

I’m using the HasRevisions trait on my Article custom entity and everything works as expected.

However, recently I’ve extended the revisions database table to also support soft deleting by adding a deleted_at column, but I don’t know how to actually extend the Revision model to support soft deleting.

Can someone please help?

Thanks a lot!

**Comment by zbiller** [comment]
As with most custom developed functionalities inside Varbox, you have the option of overwriting the bindings.   
This means that you can swap the `Varbox\Models\Revision` model with your own implementation and Varbox will take care of using your implementation everywhere.

To overwrite the `revision model` binding, go to `config/varbox/bindings.php` and change the value for `revision_model`:

```php
/*
|
| Concrete implementation for the "revision model".
| To extend or replace this functionality, change the value below with your full "revision model" FQN.
|
| Your class will have to (first option is recommended):
| - extend the "Varbox\Models\Revision" class
| - or at least implement the "Varbox\Contracts\RevisionModelContract" interface.
|
| Regardless of the concrete implementation below, you can still use it like:
| - app('revision.model') OR app('\Varbox\Contracts\RevisionModelContract')
| - or you could even use your own class as a direct implementation
|
*/

'revision_model' => \App\YourRevisionModel::class,

// 'revision_model' => \Varbox\Models\Revision::class,
```

Once that's done, you can write your soft deleting behavior inside your model.

The easiest way to conform with the requirements of the `revision model` is to extend your own model with the Varbox one, or at least implement the `Varbox\Contracts\RevisionModelContract`

```php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Varbox\Models\Revision as VarboxRevisionModel;

class YourRevisionModel extends VarboxRevisionModel
{
     use SoftDeletes;
}
```
